{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a4eb77f3-5e4c-4f9c-b35f-c29b9fb22617",
   "metadata": {},
   "source": [
    "# Lazy loading in Napari for big Datasets"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f4045377-23de-4ac8-bf49-46a233a7db3d",
   "metadata": {},
   "source": [
    "Sometimes the 3D rendering in Napari is really slow because of the size of the dataset, and is even worst if we have a big set of labels like the ones that came from cell segmentation in lightsheet datasets because we can find millions of objects that requires a 32-bits label image that can exceed the size of the raw dataset itself.\n",
    "\n",
    "For this reason, we develop this Jupyter Notebook to facilitate the visualization of this images, using a dask array of our zarr images for the lazy loading of the image."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "306b8846-2bac-43ae-958e-ae147a54ace4",
   "metadata": {},
   "source": [
    "## Setting up dependencies"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "09d936a7-f062-4b8f-94db-c93cff8b6b17",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import time\n",
    "import os\n",
    "import glob\n",
    "import dask.array as da\n",
    "import numpy as np\n",
    "import zarr as zr\n",
    "from tifffile import imread, imwrite\n",
    "from aicsimageio import AICSImage\n",
    "from aicsimageio.readers import BioformatsReader"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ae07a39f-1235-4a92-9268-797962b0b5cd",
   "metadata": {},
   "source": [
    "## Start the Dask dashboard"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e91874e4-580f-4ab1-90ee-658c391018ad",
   "metadata": {},
   "outputs": [],
   "source": [
    "from dask.distributed import Client\n",
    "\n",
    "client = Client()\n",
    "client"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "378db17f-fbe2-43d6-a0c4-a79ecc7eefe8",
   "metadata": {},
   "source": [
    "In this example, we assume that we are going to visualize a dataset together with the coresspondant labels, you can add more channels or datasets as you want. In Napari is better to  import each channel as independent layer. In this example we are going to visualize two nuclear factors, SOX9 and OCT4 with it's labels generated with Stardist. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5427dcfd-8df9-4ed4-bf77-be2112dea307",
   "metadata": {},
   "outputs": [],
   "source": [
    "Images = 'G:\\Stardist_results'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d7a18cbf-bba6-46be-89ef-100149488794",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import napari\n",
    "from napari.utils import nbscreenshot\n",
    "#import nest_asyncio\n",
    "#nest_asyncio.apply()\n",
    "\n",
    "v = napari.Viewer()\n",
    "for img in os.listdir(Images):\n",
    "    short_name = os.path.splitext(img)\n",
    "    \n",
    "    \n",
    "    \n",
    "    if img.endswith(\"_lb.tif\"):\n",
    "        store = AICSImage(Images+\"/\"+img, reader=BioformatsReader)\n",
    "        store.dask_data\n",
    "        store.xarray_dask_data\n",
    "        \n",
    "        v.add_labels(store.dask_data, name='label '+str(img[0]))\n",
    "        \n",
    "        print(os.path.join(Images, img)+' is in Napari')\n",
    "        \n",
    "        continue\n",
    "        \n",
    "    else:\n",
    "        store = AICSImage(Images+\"/\"+img, reader=BioformatsReader)\n",
    "        store.dask_data\n",
    "        store.xarray_dask_data\n",
    "        \n",
    "        v.add_image(store.dask_data, name='image '+str(img[0]), contrast_limits=[0,65535])\n",
    "        \n",
    "        print(os.path.join(Images, img)+' is in Napari')\n",
    "        \n",
    "        continue"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b03d17b7-62e3-470d-aa5f-26e97ab53724",
   "metadata": {},
   "source": [
    "## Load one by one"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9ecc8295-594c-4d22-b812-74e0a9d804d1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari_tools_menu\\__init__.py:168: FutureWarning: Public access to Window.qt_viewer is deprecated and will be removed in\n",
      "v0.5.0. It is considered an \"implementation detail\" of the napari\n",
      "application, not part of the napari viewer model. If your use case\n",
      "requires access to qt_viewer, please open an issue to discuss.\n",
      "  self.tools_menu = ToolsMenu(self, self.qt_viewer.viewer)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "G:\\Stardist_results\\EH3574_Oct4.tif is in Napari\n",
      "(1053, 1, 1, 7177, 4117) 31113737577 uint16\n"
     ]
    }
   ],
   "source": [
    "import napari\n",
    "from napari.utils import nbscreenshot\n",
    "\n",
    "v = napari.Viewer()\n",
    "\n",
    "img = r\"G:\\Stardist_results\\EH3574_Oct4.tif\"\n",
    "short_name = os.path.splitext(img)\n",
    "\n",
    "storeim = AICSImage(img, reader=BioformatsReader)\n",
    "image= storeim.dask_data\n",
    "storeim.xarray_dask_data\n",
    "        \n",
    "v.add_image(image, name='label '+str(short_name[0]))\n",
    "        \n",
    "print(img+' is in Napari')\n",
    "print(image.shape, image.size, image.dtype)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "6a92e52d-41b6-4eaf-9a43-07a14d11a377",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "G:\\Stardist_results\\EH3574_Oct4_lb.tif is in Napari\n",
      "(1053, 1, 1, 7177, 4117) 1048966505 int32\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "exception calling callback for <Future at 0x228e7b6fdc0 state=finished raised java.lang.IllegalArgumentException>\n",
      "Traceback (most recent call last):\n",
      "  File \"ImageReader.java\", line 539, in loci.formats.ImageReader.getIndex\n",
      "  File \"FormatReader.java\", line 1105, in loci.formats.FormatReader.getIndex\n",
      "  File \"FormatTools.java\", line 408, in loci.formats.FormatTools.getIndex\n",
      "  File \"FormatTools.java\", line 456, in loci.formats.FormatTools.getIndex\n",
      "Exception: Java Exception\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\_base.py\", line 330, in _invoke_callbacks\n",
      "    callback(self)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_pool.py\", line 153, in _on_done\n",
      "    request = self._get_request(future)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_pool.py\", line 189, in _get_request\n",
      "    return future.result()\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\_base.py\", line 439, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\_base.py\", line 391, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\thread.py\", line 58, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_pool.py\", line 223, in _chunk_loader_worker\n",
      "    request.load_chunks()  # loads all chunks in the request\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_request.py\", line 243, in load_chunks\n",
      "    loaded_array = np.asarray(array)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\common.py\", line 143, in __array__\n",
      "    return np.asarray(self.values, dtype=dtype)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\dataarray.py\", line 642, in values\n",
      "    return self.variable.values\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\variable.py\", line 512, in values\n",
      "    return _as_array_or_item(self._data)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\variable.py\", line 252, in _as_array_or_item\n",
      "    data = np.asarray(data)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\aicsimageio\\utils\\dask_proxy.py\", line 69, in __array__\n",
      "    return self.__wrapped__.__array__(dtype, **kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\array\\core.py\", line 1638, in __array__\n",
      "    x = self.compute()\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\base.py\", line 292, in compute\n",
      "    (result,) = compute(self, traverse=False, **kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\base.py\", line 575, in compute\n",
      "    results = schedule(dsk, keys, **kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\threaded.py\", line 81, in get\n",
      "    results = get_async(\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\local.py\", line 508, in get_async\n",
      "    raise_exception(exc, tb)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\local.py\", line 316, in reraise\n",
      "    raise exc\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\local.py\", line 221, in execute_task\n",
      "    result = _execute_task(task, data)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in <genexpr>\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\optimization.py\", line 990, in __call__\n",
      "    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 149, in get\n",
      "    result = _execute_task(task, cache)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in <genexpr>\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 113, in _execute_task\n",
      "    return [_execute_task(a, cache) for a in arg]\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 113, in <listcomp>\n",
      "    return [_execute_task(a, cache) for a in arg]\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\array\\core.py\", line 515, in _pass_extra_kwargs\n",
      "    return func(*args[len(keys) :], **kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\aicsimageio\\readers\\bioformats_reader.py\", line 525, in _dask_chunk\n",
      "    im = self._get_plane(t, c, z)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\aicsimageio\\readers\\bioformats_reader.py\", line 485, in _get_plane\n",
      "    idx = self._r.getIndex(z, c, t)\n",
      "java.lang.java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Dimension order is null\n",
      "exception calling callback for <Future at 0x228e5cb04f0 state=finished raised java.lang.IllegalArgumentException>\n",
      "Traceback (most recent call last):\n",
      "  File \"ImageReader.java\", line 539, in loci.formats.ImageReader.getIndex\n",
      "  File \"FormatReader.java\", line 1105, in loci.formats.FormatReader.getIndex\n",
      "  File \"FormatTools.java\", line 408, in loci.formats.FormatTools.getIndex\n",
      "  File \"FormatTools.java\", line 456, in loci.formats.FormatTools.getIndex\n",
      "Exception: Java Exception\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\_base.py\", line 330, in _invoke_callbacks\n",
      "    callback(self)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_pool.py\", line 153, in _on_done\n",
      "    request = self._get_request(future)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_pool.py\", line 189, in _get_request\n",
      "    return future.result()\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\_base.py\", line 439, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\_base.py\", line 391, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\thread.py\", line 58, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_pool.py\", line 223, in _chunk_loader_worker\n",
      "    request.load_chunks()  # loads all chunks in the request\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_request.py\", line 243, in load_chunks\n",
      "    loaded_array = np.asarray(array)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\common.py\", line 143, in __array__\n",
      "    return np.asarray(self.values, dtype=dtype)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\dataarray.py\", line 642, in values\n",
      "    return self.variable.values\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\variable.py\", line 512, in values\n",
      "    return _as_array_or_item(self._data)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\variable.py\", line 252, in _as_array_or_item\n",
      "    data = np.asarray(data)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\aicsimageio\\utils\\dask_proxy.py\", line 69, in __array__\n",
      "    return self.__wrapped__.__array__(dtype, **kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\array\\core.py\", line 1638, in __array__\n",
      "    x = self.compute()\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\base.py\", line 292, in compute\n",
      "    (result,) = compute(self, traverse=False, **kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\base.py\", line 575, in compute\n",
      "    results = schedule(dsk, keys, **kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\threaded.py\", line 81, in get\n",
      "    results = get_async(\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\local.py\", line 508, in get_async\n",
      "    raise_exception(exc, tb)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\local.py\", line 316, in reraise\n",
      "    raise exc\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\local.py\", line 221, in execute_task\n",
      "    result = _execute_task(task, data)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in <genexpr>\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\optimization.py\", line 990, in __call__\n",
      "    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 149, in get\n",
      "    result = _execute_task(task, cache)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in <genexpr>\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 113, in _execute_task\n",
      "    return [_execute_task(a, cache) for a in arg]\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 113, in <listcomp>\n",
      "    return [_execute_task(a, cache) for a in arg]\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\array\\core.py\", line 515, in _pass_extra_kwargs\n",
      "    return func(*args[len(keys) :], **kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\aicsimageio\\readers\\bioformats_reader.py\", line 525, in _dask_chunk\n",
      "    im = self._get_plane(t, c, z)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\aicsimageio\\readers\\bioformats_reader.py\", line 485, in _get_plane\n",
      "    idx = self._r.getIndex(z, c, t)\n",
      "java.lang.java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Dimension order is null\n",
      "exception calling callback for <Future at 0x228e81dbb20 state=finished raised java.lang.IllegalArgumentException>\n",
      "Traceback (most recent call last):\n",
      "  File \"ImageReader.java\", line 539, in loci.formats.ImageReader.getIndex\n",
      "  File \"FormatReader.java\", line 1105, in loci.formats.FormatReader.getIndex\n",
      "  File \"FormatTools.java\", line 408, in loci.formats.FormatTools.getIndex\n",
      "  File \"FormatTools.java\", line 456, in loci.formats.FormatTools.getIndex\n",
      "Exception: Java Exception\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\_base.py\", line 330, in _invoke_callbacks\n",
      "    callback(self)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_pool.py\", line 153, in _on_done\n",
      "    request = self._get_request(future)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_pool.py\", line 189, in _get_request\n",
      "    return future.result()\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\_base.py\", line 439, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\_base.py\", line 391, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\thread.py\", line 58, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_pool.py\", line 223, in _chunk_loader_worker\n",
      "    request.load_chunks()  # loads all chunks in the request\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_request.py\", line 243, in load_chunks\n",
      "    loaded_array = np.asarray(array)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\common.py\", line 143, in __array__\n",
      "    return np.asarray(self.values, dtype=dtype)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\dataarray.py\", line 642, in values\n",
      "    return self.variable.values\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\variable.py\", line 512, in values\n",
      "    return _as_array_or_item(self._data)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\variable.py\", line 252, in _as_array_or_item\n",
      "    data = np.asarray(data)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\aicsimageio\\utils\\dask_proxy.py\", line 69, in __array__\n",
      "    return self.__wrapped__.__array__(dtype, **kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\array\\core.py\", line 1638, in __array__\n",
      "    x = self.compute()\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\base.py\", line 292, in compute\n",
      "    (result,) = compute(self, traverse=False, **kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\base.py\", line 575, in compute\n",
      "    results = schedule(dsk, keys, **kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\threaded.py\", line 81, in get\n",
      "    results = get_async(\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\local.py\", line 508, in get_async\n",
      "    raise_exception(exc, tb)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\local.py\", line 316, in reraise\n",
      "    raise exc\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\local.py\", line 221, in execute_task\n",
      "    result = _execute_task(task, data)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in <genexpr>\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\optimization.py\", line 990, in __call__\n",
      "    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 149, in get\n",
      "    result = _execute_task(task, cache)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in <genexpr>\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 113, in _execute_task\n",
      "    return [_execute_task(a, cache) for a in arg]\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 113, in <listcomp>\n",
      "    return [_execute_task(a, cache) for a in arg]\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\core.py\", line 119, in _execute_task\n",
      "    return func(*(_execute_task(a, cache) for a in args))\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\dask\\array\\core.py\", line 515, in _pass_extra_kwargs\n",
      "    return func(*args[len(keys) :], **kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\aicsimageio\\readers\\bioformats_reader.py\", line 525, in _dask_chunk\n",
      "    im = self._get_plane(t, c, z)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\aicsimageio\\readers\\bioformats_reader.py\", line 485, in _get_plane\n",
      "    idx = self._r.getIndex(z, c, t)\n",
      "java.lang.java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Dimension order is null\n",
      "exception calling callback for <Future at 0x228e821d400 state=finished raised java.nio.channels.ClosedChannelException>\n",
      "Traceback (most recent call last):\n",
      "  File \"ImageReader.java\", line 849, in loci.formats.ImageReader.setId\n",
      "  File \"TiffDelegateReader.java\", line 92, in loci.formats.in.TiffDelegateReader.setId\n",
      "  File \"FormatReader.java\", line 1421, in loci.formats.FormatReader.setId\n",
      "  File \"BaseTiffReader.java\", line 591, in loci.formats.in.BaseTiffReader.initFile\n",
      "  File \"MinimalTiffReader.java\", line 483, in loci.formats.in.MinimalTiffReader.initFile\n",
      "  File \"TiffParser.java\", line 526, in loci.formats.tiff.TiffParser.fillInIFD\n",
      "  File \"TiffParser.java\", line 607, in loci.formats.tiff.TiffParser.getIFDValue\n",
      "  File \"RandomAccessInputStream.java\", line 574, in loci.common.RandomAccessInputStream.readUnsignedInt\n",
      "  File \"RandomAccessInputStream.java\", line 564, in loci.common.RandomAccessInputStream.readInt\n",
      "  File \"NIOFileHandle.java\", line 410, in loci.common.NIOFileHandle.readInt\n",
      "  File \"NIOFileHandle.java\", line 647, in loci.common.NIOFileHandle.buffer\n",
      "  File \"NIOByteBufferProvider.java\", line 112, in loci.common.NIOByteBufferProvider.allocate\n",
      "  File \"NIOByteBufferProvider.java\", line 127, in loci.common.NIOByteBufferProvider.allocateDirect\n",
      "  File \"FileChannelImpl.java\", line 790, in sun.nio.ch.FileChannelImpl.read\n",
      "  File \"FileChannelImpl.java\", line 150, in sun.nio.ch.FileChannelImpl.ensureOpen\n",
      "Exception: Java Exception\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\_base.py\", line 330, in _invoke_callbacks\n",
      "    callback(self)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_pool.py\", line 153, in _on_done\n",
      "    request = self._get_request(future)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_pool.py\", line 189, in _get_request\n",
      "    return future.result()\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\_base.py\", line 439, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\_base.py\", line 391, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\concurrent\\futures\\thread.py\", line 58, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_pool.py\", line 223, in _chunk_loader_worker\n",
      "    request.load_chunks()  # loads all chunks in the request\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\napari\\components\\experimental\\chunk\\_request.py\", line 243, in load_chunks\n",
      "    loaded_array = np.asarray(array)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\common.py\", line 143, in __array__\n",
      "    return np.asarray(self.values, dtype=dtype)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\dataarray.py\", line 642, in values\n",
      "    return self.variable.values\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\variable.py\", line 512, in values\n",
      "    return _as_array_or_item(self._data)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\xarray\\core\\variable.py\", line 252, in _as_array_or_item\n",
      "    data = np.asarray(data)\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\aicsimageio\\utils\\dask_proxy.py\", line 68, in __array__\n",
      "    with self._file_ctx if self._file_ctx.closed else nullcontext():  # type: ignore\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\aicsimageio\\readers\\bioformats_reader.py\", line 440, in __enter__\n",
      "    self.open()\n",
      "  File \"C:\\Users\\Linux\\.conda\\envs\\bio11\\lib\\site-packages\\aicsimageio\\readers\\bioformats_reader.py\", line 356, in open\n",
      "    self._r.setId(self._path)\n",
      "java.nio.channels.java.nio.channels.ClosedChannelException: java.nio.channels.ClosedChannelException\n"
     ]
    }
   ],
   "source": [
    "lbl = r\"G:\\Stardist_results\\EH3574_Oct4_lb.tif\"\n",
    "short_namel = os.path.splitext(lbl)\n",
    "\n",
    "storelb = AICSImage(lbl, reader=BioformatsReader)\n",
    "labels = storelb.dask_data\n",
    "storelb.xarray_dask_data\n",
    "        \n",
    "v.add_labels(labels, name='label '+str(short_namel[0]))\n",
    "        \n",
    "print(lbl+' is in Napari')\n",
    "print(labels.shape, labels.size, labels.dtype)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ce62a483-89df-4820-b736-e89fa619ddd3",
   "metadata": {},
   "outputs": [],
   "source": [
    "images = (r\"D:\\EHG\\Gonad\\Raw\\19-48-26_EH3574_PCW106_5-COUPTFII_6-Oct4_7-Sox9_12x_1z_STITCHED.ome_C1.zarr\",r\"D:\\EHG\\Gonad\\Raw\\19-48-26_EH3574_PCW106_5-COUPTFII_6-Oct4_7-Sox9_12x_1z_STITCHED.ome_C0.zarr\")\n",
    "\n",
    "Oct4 = (zr.load(images[0]))\n",
    "lazy_Oct4 = (lazy_load(images[0]))\n",
    "lazy_Sox9 = (lazy_load(images[1]))\n",
    "\n",
    "dask_Oct4 = da.from_delayed(lazy_Oct4, shape=Oct4.shape, dtype=Oct4.dtype)\n",
    "dask_Sox9 = da.from_delayed(lazy_Sox9, shape=Oct4.shape, dtype=Oct4.dtype)\n",
    "\n",
    "dask_Oct4.shape\n",
    "dask_Sox9.shape\n",
    "\n",
    "print(Oct4.shape)\n",
    "dask_Oct4        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "33b84ce6-7c14-4110-bb75-48b745105803",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e2f08948-a4dc-44b1-97d7-bfdcb0495f34",
   "metadata": {},
   "outputs": [],
   "source": [
    "dask_Sox9"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "511042b2-3fad-441c-b45f-827d463119f7",
   "metadata": {},
   "outputs": [],
   "source": [
    "desired_chunksize = np.array([10,2,2])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e0c442e6-949a-4349-a088-9f577f442523",
   "metadata": {},
   "outputs": [],
   "source": [
    "rechunked_Oct4 = dask_Oct4.rechunk(desired_chunksize)\n",
    "rechunked_Oct4"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0dd8392d-955f-49ac-9321-63ff301fda06",
   "metadata": {},
   "outputs": [],
   "source": [
    "import napari\n",
    "from napari.utils import nbscreenshot\n",
    "import nest_asyncio\n",
    "nest_asyncio.apply()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9cc7040e-4739-42f9-b655-934a2559af4f",
   "metadata": {},
   "outputs": [],
   "source": [
    "v = napari.Viewer()\n",
    "v.add_image(dask_Oct4, name=\"Oct4\", contrast_limits=[0,1], cache=False)\n",
    "v.add_image(dask_Sox9, name=\"Sox9\", contrast_limits=[0,1], cache=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "08ed3280-dbe8-4aa8-94d9-4d2cac845ac6",
   "metadata": {},
   "outputs": [],
   "source": [
    "labels = (r\"G:\\Stardist_results\\LblImg_19-48-26_EH3574_PCW106_5-COUPTFII_6-Oct4_7-Sox9_12x_1z_STITCHED.ome_C1.tif1.zarr\", r\"G:\\Stardist_results\\LblImg_19-48-26_EH3574_PCW106_5-COUPTFII_6-Oct4_7-Sox9_12x_1z_STITCHED_C0_lbl.tif1.zarr\")\n",
    "\n",
    "Oct4l = (zr.load(labels[0]))\n",
    "lazy_labels = [lazy_load(lbl) for lbl in labels]\n",
    "dask_labels = [\n",
    "    da.from_delayed(delayed_reader, shape=Oct4l.shape, dtype=Oct4l.dtype)\n",
    "    for delayed_reader in lazy_labels\n",
    "]\n",
    "\n",
    "lstack = da.stack(dask_labels, axis=0)\n",
    "lstack.shape\n",
    "\n",
    "lstack"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7fbe440f-44b1-413f-8e56-8f0501ff5ce3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1b6aedb9-7dbf-434f-b7ab-f7e535cf5a4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import napari\n",
    "from napari.utils import nbscreenshot"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5faad54b-6e2c-49d8-9c0c-fc7181260ef0",
   "metadata": {},
   "outputs": [],
   "source": [
    "v = napari.Viewer()\n",
    "v.add_image(istack, contrast_limits=[0,2000], multiscale=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a4796280-3889-4097-a61b-8e770ae7264b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
